In [1]:
# https://dplyr.tidyverse.org/reference/pull.html

from plyrda.data import starwars, mtcars
from plyrda.all import *

In [2]:
mtcars >> pull(-1)

array([4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, 1, 1, 2,
       2, 4, 2, 1, 2, 2, 4, 6, 8, 2])

In [3]:
mtcars >> pull(-1, to_list=True)

[4,
 4,
 1,
 1,
 2,
 1,
 4,
 2,
 2,
 4,
 4,
 3,
 3,
 3,
 4,
 4,
 4,
 1,
 2,
 1,
 1,
 2,
 2,
 4,
 2,
 1,
 2,
 2,
 4,
 6,
 8,
 2]

In [4]:
mtcars >> pull(0)

array([21. , 21. , 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8,
       16.4, 17.3, 15.2, 10.4, 10.4, 14.7, 32.4, 30.4, 33.9, 21.5, 15.5,
       15.2, 13.3, 19.2, 27.3, 26. , 30.4, 15.8, 19.7, 15. , 21.4])

In [5]:
mtcars >> pull(f.cyl)

array([6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8,
       8, 8, 8, 4, 4, 4, 8, 6, 8, 4])

In [6]:
df = tibble(x=range(1, 11), y=range(10, 0, -1))
df >> mutate(z=f.x*f.y) >> pull()

array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])

In [7]:
list(starwars >> pull(f.height, f.name))

[('Luke Skywalker', 172.0),
 ('C-3PO', 167.0),
 ('R2-D2', 96.0),
 ('Darth Vader', 202.0),
 ('Leia Organa', 150.0),
 ('Owen Lars', 178.0),
 ('Beru Whitesun lars', 165.0),
 ('R5-D4', 97.0),
 ('Biggs Darklighter', 183.0),
 ('Obi-Wan Kenobi', 182.0),
 ('Anakin Skywalker', 188.0),
 ('Wilhuff Tarkin', 180.0),
 ('Chewbacca', 228.0),
 ('Han Solo', 180.0),
 ('Greedo', 173.0),
 ('Jabba Desilijic Tiure', 175.0),
 ('Wedge Antilles', 170.0),
 ('Jek Tono Porkins', 180.0),
 ('Yoda', 66.0),
 ('Palpatine', 170.0),
 ('Boba Fett', 183.0),
 ('IG-88', 200.0),
 ('Bossk', 190.0),
 ('Lando Calrissian', 177.0),
 ('Lobot', 175.0),
 ('Ackbar', 180.0),
 ('Mon Mothma', 150.0),
 ('Arvel Crynyd', nan),
 ('Wicket Systri Warrick', 88.0),
 ('Nien Nunb', 160.0),
 ('Qui-Gon Jinn', 193.0),
 ('Nute Gunray', 191.0),
 ('Finis Valorum', 170.0),
 ('Jar Jar Binks', 196.0),
 ('Roos Tarpals', 224.0),
 ('Rugor Nass', 206.0),
 ('Ric Olié', 183.0),
 ('Watto', 137.0),
 ('Sebulba', 112.0),
 ('Quarsh Panaka', 183.0),
 ('Shmi Skywalker'