In [1]:
# https://dplyr.tidyverse.org/reference/lead-lag.html
%run nb_helpers.py

from datar.all import *

nb_header(lead, lag, book='lead-lag')

### <div style="background-color: #EEE; padding: 5px 0 8px 0">★ lead</div>

##### Find next values in a vector

##### Args:
&emsp;&emsp;`series`: Vector of values  
&emsp;&emsp;`n`: Positive integer of length 1, giving the number of positions to  
&emsp;&emsp;&emsp;&emsp;lead or lag by  

&emsp;&emsp;`default`: Value used for non-existent rows.  
&emsp;&emsp;`order_by`: Override the default ordering to use another vector or column  

##### Returns:
&emsp;&emsp;Lead or lag values with default values filled to series.  


### <div style="background-color: #EEE; padding: 5px 0 8px 0">★ lag</div>

##### Find previous values in a vector

See lead()  


In [2]:
x = [1,2,3,4,5]

lag(x)

array([nan,  1.,  2.,  3.,  4.])

In [3]:
lead(x)

array([ 2.,  3.,  4.,  5., nan])

In [4]:
tibble(behind=lag(x), x=x, ahead=lead(x))

behind       x     ahead
  <float64> <int64> <float64>
0       NaN       1       2.0
1       1.0       2       3.0
2       2.0       3       4.0
3       3.0       4       5.0
4       4.0       5       NaN

In [5]:
lag(x, n=1)

array([nan,  1.,  2.,  3.,  4.])

In [6]:
lag(x, n=2)

array([nan, nan,  1.,  2.,  3.])

In [7]:
lead(x, n=1)

array([ 2.,  3.,  4.,  5., nan])

In [8]:
lead(x, n=2)

array([ 3.,  4.,  5., nan, nan])

In [9]:
lag(x, default=0)

array([0, 1, 2, 3, 4])

In [10]:
lead(x, default=6)

array([2, 3, 4, 5, 6])

In [11]:
scrambled = slice_sample(
    tibble(year=[2000, 2001, 2002, 2003, 2004, 2005], 
           value=[a**2 for a in range(6)]), 
    prop=1
) 

scrambled >> mutate(previous_year_value = lag(f.value)) >> arrange(f.year)

year   value  previous_year_value
  <int64> <int64>            <float64>
0    2000       0                  1.0
1    2001       1                  4.0
2    2002       4                 16.0
3    2003       9                 25.0
4    2004      16                  NaN
5    2005      25                  0.0

In [12]:
# Use this for lag(value, order_by = year) instead
scrambled >> mutate(previous_year_value = lag(f.value, order_by=f.year)) >> arrange(f.year)


year   value  previous_year_value
  <int64> <int64>            <float64>
0    2000       0                  NaN
1    2001       1                  0.0
2    2002       4                  1.0
3    2003       9                  4.0
4    2004      16                  9.0
5    2005      25                 16.0